version: "3.1"
services:
  redis:
    image: redis
    restart: always
    ports:
      - 6379:6379
    volumes:
      - redisdata:/var/lib/redis
    networks:
      - esnet

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: example
      POSTGRES_DB: documentsDB
    ports:
      - 5432:5432
    volumes:
      - postgresdata:/var/lib/postgresql/data
    networks:
      - esnet

volumes:
  redisdata:
    driver: local
  postgresdata:
    driver: local

networks:
  esnet:

    # --docker run -p 80:80 \                                      
    # -e 'PGADMIN_DEFAULT_EMAIL=user@domain.com' \
    # -e 'PGADMIN_DEFAULT_PASSWORD=SuperSecret' \
    # -d dpage/pgadmin4