version: "3.1"
services:
  redis:
    image: redis
    restart: always
    ports:
      - 6379:6379
    volumes:
      - redisdata:/var/lib/redis
    networks:
      - esnet

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: example
      POSTGRES_DB: documentsDB
    ports:
      - 5432:5432
    volumes:
      - postgresdata:/var/lib/postgresql/data
    networks:
      - esnet

  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.8.0
    container_name: es01
    environment:
      - node.name=es01
      - cluster.initial_master_nodes=es01
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "http.port=9200"
      - "http.publish_host=_local_"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata01:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - esnet

  kib01:
    image: docker.elastic.co/kibana/kibana:7.8.0
    container_name: kib01
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_URL: http://es01:9200
      ELASTICSEARCH_HOSTS: http://es01:9200
    networks:
      - esnet
    depends_on:
      - es01

  web:
    build: .
    ports:
      - "5000:5000"
      - "5001:5001"
    depends_on:
      - postgres
      - es01
      - redis
    networks:
      - esnet

volumes:
  esdata01:
    driver: local
  redisdata:
    driver: local
  postgresdata:
    driver: local

networks:
  esnet:
